# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import analytics_pb2 as analytics__pb2

GRPC_GENERATED_VERSION = '1.64.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in analytics_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class AnalyticsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TrackClick = channel.unary_unary(
                '/analytics.Analytics/TrackClick',
                request_serializer=analytics__pb2.TrackClickRequest.SerializeToString,
                response_deserializer=analytics__pb2.TrackClickResponse.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/analytics.Analytics/GetStats',
                request_serializer=analytics__pb2.GetStatsRequest.SerializeToString,
                response_deserializer=analytics__pb2.GetStatsResponse.FromString,
                _registered_method=True)
        self.DetectMalicious = channel.unary_unary(
                '/analytics.Analytics/DetectMalicious',
                request_serializer=analytics__pb2.DetectRequest.SerializeToString,
                response_deserializer=analytics__pb2.DetectResponse.FromString,
                _registered_method=True)
        self.GetFlaggedURLs = channel.unary_unary(
                '/analytics.Analytics/GetFlaggedURLs',
                request_serializer=analytics__pb2.EmptyRequest.SerializeToString,
                response_deserializer=analytics__pb2.FlaggedURLsResponse.FromString,
                _registered_method=True)


class AnalyticsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TrackClick(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectMalicious(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFlaggedURLs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalyticsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TrackClick': grpc.unary_unary_rpc_method_handler(
                    servicer.TrackClick,
                    request_deserializer=analytics__pb2.TrackClickRequest.FromString,
                    response_serializer=analytics__pb2.TrackClickResponse.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=analytics__pb2.GetStatsRequest.FromString,
                    response_serializer=analytics__pb2.GetStatsResponse.SerializeToString,
            ),
            'DetectMalicious': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectMalicious,
                    request_deserializer=analytics__pb2.DetectRequest.FromString,
                    response_serializer=analytics__pb2.DetectResponse.SerializeToString,
            ),
            'GetFlaggedURLs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFlaggedURLs,
                    request_deserializer=analytics__pb2.EmptyRequest.FromString,
                    response_serializer=analytics__pb2.FlaggedURLsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'analytics.Analytics', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('analytics.Analytics', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Analytics(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TrackClick(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.Analytics/TrackClick',
            analytics__pb2.TrackClickRequest.SerializeToString,
            analytics__pb2.TrackClickResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.Analytics/GetStats',
            analytics__pb2.GetStatsRequest.SerializeToString,
            analytics__pb2.GetStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectMalicious(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.Analytics/DetectMalicious',
            analytics__pb2.DetectRequest.SerializeToString,
            analytics__pb2.DetectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFlaggedURLs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.Analytics/GetFlaggedURLs',
            analytics__pb2.EmptyRequest.SerializeToString,
            analytics__pb2.FlaggedURLsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
