# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analytics.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61nalytics.proto\x12\tanalytics\":\n\x11TrackClickRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\n\n\x02ip\x18\x03 \x01(\t\":\n\x12TrackClickResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x13\n\x0b\x66raud_score\x18\x02 \x01(\x01\"\x1f\n\x0fGetStatsRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"\"\n\x10GetStatsResponse\x12\x0e\n\x06\x63licks\x18\x01 \x01(\x05\"(\n\rDetectRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\"H\n\x0e\x44\x65tectResponse\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x13\n\x0b\x66raud_score\x18\x02 \x01(\x01\x12\x14\n\x0cis_malicious\x18\x03 \x01(\x08\"\x0e\n\x0c\x45mptyRequest\"3\n\x0f\x46laggedURLEntry\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x13\n\x0b\x66raud_score\x18\x02 \x01(\x01\"B\n\x13\x46laggedURLsResponse\x12+\n\x07\x66lagged\x18\x01 \x03(\x0b\x32\x1a.analytics.FlaggedURLEntry2\xae\x02\n\tAnalytics\x12I\n\nTrackClick\x12\x1c.analytics.TrackClickRequest\x1a\x1d.analytics.TrackClickResponse\x12\x43\n\x08GetStats\x12\x1a.analytics.GetStatsRequest\x1a\x1b.analytics.GetStatsResponse\x12\x46\n\x0f\x44\x65tectMalicious\x12\x18.analytics.DetectRequest\x1a\x19.analytics.DetectResponse\x12I\n\x0eGetFlaggedURLs\x12\x17.analytics.EmptyRequest\x1a\x1e.analytics.FlaggedURLsResponseB\x1eZ\x1curlshortener/proto/analyticsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analytics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\034urlshortener/proto/analytics'
  _globals['_TRACKCLICKREQUEST']._serialized_start=30
  _globals['_TRACKCLICKREQUEST']._serialized_end=88
  _globals['_TRACKCLICKRESPONSE']._serialized_start=90
  _globals['_TRACKCLICKRESPONSE']._serialized_end=148
  _globals['_GETSTATSREQUEST']._serialized_start=150
  _globals['_GETSTATSREQUEST']._serialized_end=181
  _globals['_GETSTATSRESPONSE']._serialized_start=183
  _globals['_GETSTATSRESPONSE']._serialized_end=217
  _globals['_DETECTREQUEST']._serialized_start=219
  _globals['_DETECTREQUEST']._serialized_end=259
  _globals['_DETECTRESPONSE']._serialized_start=261
  _globals['_DETECTRESPONSE']._serialized_end=333
  _globals['_EMPTYREQUEST']._serialized_start=335
  _globals['_EMPTYREQUEST']._serialized_end=349
  _globals['_FLAGGEDURLENTRY']._serialized_start=351
  _globals['_FLAGGEDURLENTRY']._serialized_end=402
  _globals['_FLAGGEDURLSRESPONSE']._serialized_start=404
  _globals['_FLAGGEDURLSRESPONSE']._serialized_end=470
  _globals['_ANALYTICS']._serialized_start=473
  _globals['_ANALYTICS']._serialized_end=775
# @@protoc_insertion_point(module_scope)
