CREATE TABLE IF NOT EXISTS urls(
	id INT AUTO_INCREMENT PRIMARY KEY,
	short_code VARCHAR(100) NOT NULL UNIQUE,
	long_url TEXT NOT NULL,
	expires_at TIMESTAMP NOT NULL,
	is_active TINYINT(1) DEFAULT 1,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);